(define (domain brava-island-adventure)
(:requirements :strips :typing)
(:types player location item trap puzzle ally)
(:predicates
    (player-at ?p - player ?l - location)
    (has ?p - player ?i - item)
    (ally-present ?a - ally ?l - location)
    (wounded ?p - player)
    (poisoned ?p - player)
    (medallion-found ?p - player)
    (native-trust-earned ?p - player)
    (puzzle-solved ?p - player)
    (treasure-claimed ?p - player)
    (temple-accessible)
    (village-entered ?p - player)
    (trap-active ?t - trap ?l - location)
    (trap-triggered ?t - trap ?l - location)
    (puzzle-active ?z - puzzle ?l - location)
    (puzzle-failed ?p - player)
    (fatally-injured ?p - player)
    (trapped ?p - player))
(:action venture-into-jungle-edge-main-trail
    :parameters (?p - player ?shore - location ?jungle - location)
    :precondition (and (player-at ?p ?shore))
    :effect (and (player-at ?p ?jungle) (not (player-at ?p ?shore)))
)
(:action scout-shoreline-for-safer-path
    :parameters (?p - player ?shore - location ?jungle - location)
    :precondition (and (player-at ?p ?shore))
    :effect (and (player-at ?p ?jungle) (not (player-at ?p ?shore)) (not (wounded ?p)))
)
(:action set-up-temporary-camp
    :parameters (?p - player ?shore - location)
    :precondition (and (player-at ?p ?shore))
    :effect (and (player-at ?p ?shore) (not (wounded ?p)))
)
(:action take-direct-path-to-collapsed-cave-ignoring-warnings
    :parameters (?p - player ?jungle - location ?cave - location ?trap - trap)
    :precondition (and (player-at ?p ?jungle) (trap-active ?trap ?jungle))
    :effect (and (player-at ?p ?cave) (wounded ?p) (trap-triggered ?trap ?jungle) (not (player-at ?p ?jungle)))
)
(:action search-carefully-for-traps-and-safe-routes
    :parameters (?p - player ?jungle - location ?cave - location)
    :precondition (and (player-at ?p ?jungle))
    :effect (and (player-at ?p ?cave) (not (wounded ?p)) (not (player-at ?p ?jungle)))
)
(:action call-out-for-natives
    :parameters (?p - player ?jungle - location ?ally - ally)
    :precondition (and (player-at ?p ?jungle))
    :effect (and (player-at ?p ?jungle) (ally-present ?ally ?jungle))
)
(:action proceed-cautiously-along-hidden-trail
    :parameters (?p - player ?jungle - location ?cave - location)
    :precondition (and (player-at ?p ?jungle))
    :effect (and (player-at ?p ?cave) (not (wounded ?p)) (not (player-at ?p ?jungle)))
)
(:action pause-to-gather-plants-and-water
    :parameters (?p - player ?jungle - location)
    :precondition (and (player-at ?p ?jungle))
    :effect (and (player-at ?p ?jungle) (not (wounded ?p)))
)
(:action push-forward-despite-wound
    :parameters (?p - player ?cave - location)
    :precondition (and (wounded ?p))
    :effect (and (player-at ?p ?cave) (wounded ?p) (medallion-found ?p))
)
(:action retreat-to-jungle-edge-to-tend-injury
    :parameters (?p - player ?jungle - location ?cave - location)
    :precondition (and (wounded ?p) (player-at ?p ?cave))
    :effect (and (player-at ?p ?jungle) (not (wounded ?p)) (not (player-at ?p ?cave)))
)
(:action find-medicinal-plants-to-counter-poison
    :parameters (?p - player ?location - location)
    :precondition (and (wounded ?p))
    :effect (and (not (poisoned ?p)) (not (wounded ?p)) (player-at ?p ?location))
)
(:action enter-collapsed-cave-to-search-medallion
    :parameters (?p - player ?cave - location)
    :precondition (and (player-at ?p ?cave))
    :effect (and (medallion-found ?p))
)
(:action circle-around-cave-for-alternative-entrances
    :parameters (?p - player ?cave - location ?ally - ally)
    :precondition (and (player-at ?p ?cave))
    :effect (and (ally-present ?ally ?cave))
)
(:action proceed-to-village-to-present-medallion
    :parameters (?p - player ?village - location)
    :precondition (and (medallion-found ?p))
    :effect (and (village-entered ?p))
)
(:action rest-and-tend-wounds-before-village
    :parameters (?p - player ?location - location)
    :precondition (and (wounded ?p))
    :effect (and (not (wounded ?p)) (player-at ?p ?location))
)
(:action seek-native-ally-to-accompany-to-village
    :parameters (?p - player ?ally - ally ?village - location)
    :precondition (and (ally-present ?ally ?village))
    :effect (and (ally-present ?ally ?village) (village-entered ?p))
)
(:action enter-village-alone-hoping-to-prove-yourself
    :parameters (?p - player ?village - location)
    :precondition (and )
    :effect (and (village-entered ?p))
)
(:action earn-natives-trust-by-presenting-medallion
    :parameters (?p - player ?ally - ally ?village - location)
    :precondition (and (village-entered ?p) (medallion-found ?p))
    :effect (and (native-trust-earned ?p) (ally-present ?ally ?village))
)
(:action travel-with-natives-guidance-to-temple-outskirts
    :parameters (?p - player)
    :precondition (and (native-trust-earned ?p))
    :effect (and (temple-accessible))
)
(:action explore-village-for-info-and-supplies
    :parameters (?p - player ?ally - ally ?village - location)
    :precondition (and (village-entered ?p))
    :effect (and (ally-present ?ally ?village))
)
(:action rest-in-village-to-recover
    :parameters (?p - player ?location - location)
    :precondition (and (wounded ?p))
    :effect (and (not (wounded ?p)) (player-at ?p ?location))
)
(:action attempt-to-flee-hostile-village
    :parameters (?p - player ?village - location ?jungle - location)
    :precondition (and (village-entered ?p))
    :effect (and (wounded ?p) (player-at ?p ?jungle) (not (village-entered ?p)))
)
(:action try-to-negotiate-peace-with-hostile-natives
    :parameters (?p - player ?village - location)
    :precondition (and (village-entered ?p))
    :effect (and (wounded ?p))
)
(:action reach-temple-outskirts-with-ally
    :parameters (?p - player ?ally - ally)
    :precondition (and (native-trust-earned ?p) (ally-present ?ally ?p))
    :effect (and (temple-accessible))
)
(:action attempt-to-solve-altar-puzzle
    :parameters (?p - player ?puzzle - puzzle)
    :precondition (and (temple-accessible) (medallion-found ?p))
    :effect (and (puzzle-solved ?p))
)
(:action explore-temple-grounds-for-clues
    :parameters (?p - player ?ally - ally)
    :precondition (and (temple-accessible) (ally-present ?ally ?p))
    :effect (and (ally-present ?ally ?p))
)
(:action rest-briefly-to-prepare-for-puzzle
    :parameters (?p - player ?location - location)
    :precondition (and (wounded ?p))
    :effect (and (not (wounded ?p)) (player-at ?p ?location))
)
(:action trigger-poison-dart-trap-in-temple
    :parameters (?p - player ?trap - trap)
    :precondition (and (temple-accessible) (not (puzzle-solved ?p)))
    :effect (and (poisoned ?p) (fatally-injured ?p))
)
(:action claim-treasure-and-prepare-to-leave
    :parameters (?p - player)
    :precondition (and (puzzle-solved ?p) (native-trust-earned ?p))
    :effect (and (treasure-claimed ?p))
)
)
