(define (domain brava-island-adventure)
  (:requirements :strips :typing)
  (:types player location item trap puzzle ally)
  (:predicates
    (player-at ?p - player ?l - location)
    (has ?p - player ?i - item)
    (ally-present ?a - ally ?l - location)
    (wounded ?p - player)
    (medallion-found)
    (native-trust-earned)
    (puzzle-solved)
    (treasure-claimed)
    (temple-accessible)
    (trap-active ?t - trap ?l - location)
    (trap-triggered ?t - trap ?l - location)
    (at-jungle-edge)
    (at-shore)
    (at-village)
    (at-collapsed-cave)
    (lost-in-jungle)
    (fatally-injured ?p - player)
    (trapped ?p - player)
  )
  (:action venture-into-dense-jungle
    :parameters (?p - player ?shore - location ?jungle_edge - location)
    :precondition (and (player-at ?p ?shore) (at-shore))
    :effect (and (not (player-at ?p ?shore)) (player-at ?p ?jungle_edge) (not (at-shore)) (at-jungle-edge))
  )
  (:action scout-along-shoreline
    :parameters (?p - player ?shore - location ?jungle_edge - location)
    :precondition (and (player-at ?p ?shore) (at-shore) (not (wounded ?p)))
    :effect (and (not (player-at ?p ?shore)) (player-at ?p ?jungle_edge) (not (at-shore)) (at-jungle-edge) (not (wounded ?p)))
  )
  (:action rest-and-prepare-supplies
    :parameters (?p - player ?shore - location)
    :precondition (and (player-at ?p ?shore) (at-shore) (not (wounded ?p)))
    :effect (and (player-at ?p ?shore) (at-shore) (not (wounded ?p)))
  )
  (:action call-out-for-natives
    :parameters (?p - player ?shore - location ?native - ally)
    :precondition (and (player-at ?p ?shore) (at-shore) (not (ally-present ?native ?shore)))
    :effect (and (ally-present ?native ?shore))
  )
  (:action proceed-cautiously-to-collapsed-cave
    :parameters (?p - player ?jungle_edge - location ?cave - location)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge))
    :effect (and (not (player-at ?p ?jungle_edge)) (player-at ?p ?cave) (not (at-jungle-edge)) (at-collapsed-cave))
  )
  (:action explore-jungle-outskirts-for-allies
    :parameters (?p - player ?jungle_edge - location ?native - ally)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge))
    :effect (and (ally-present ?native ?jungle_edge))
  )
  (:action set-simple-traps
    :parameters (?p - player ?jungle_edge - location ?trap - trap)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge) (not (wounded ?p)))
    :effect (and (trap-active ?trap ?jungle_edge) (not (wounded ?p)))
  )
  (:action head-into-jungle-to-collapsed-cave
    :parameters (?p - player ?jungle_edge - location ?cave - location)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge))
    :effect (and (not (player-at ?p ?jungle_edge)) (player-at ?p ?cave) (not (at-jungle-edge)) (at-collapsed-cave))
  )
  (:action follow-smoke-to-village
    :parameters (?p - player ?jungle_edge - location ?village - location)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge))
    :effect (and (not (player-at ?p ?jungle_edge)) (player-at ?p ?village) (not (at-jungle-edge)) (at-village))
  )
  (:action set-up-temporary-camp
    :parameters (?p - player ?jungle_edge - location)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge) (not (wounded ?p)))
    :effect (and (player-at ?p ?jungle_edge) (at-jungle-edge) (not (wounded ?p)))
  )
  (:action search-carefully-for-medallion
    :parameters (?p - player ?cave - location ?medallion - item)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave) (not (wounded ?p)))
    :effect (and (medallion-found) (has ?p ?medallion))
  )
  (:action rush-through-cave-and-get-wounded
    :parameters (?p - player ?cave - location ?trap - trap)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave) (not (wounded ?p)))
    :effect (and (wounded ?p) (trap-triggered ?trap ?cave))
  )
  (:action retreat-to-jungle-edge
    :parameters (?p - player ?cave - location ?jungle_edge - location)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave))
    :effect (and (not (player-at ?p ?cave)) (player-at ?p ?jungle_edge) (not (at-collapsed-cave)) (at-jungle-edge))
  )
  (:action enter-cave-with-ally
    :parameters (?p - player ?native - ally ?cave - location)
    :precondition (and (player-at ?p ?cave) (ally-present ?native ?cave) (at-collapsed-cave) (not (medallion-found)))
    :effect (and)
  )
  (:action take-medallion-and-go-to-village-with-ally
    :parameters (?p - player ?native - ally ?cave - location ?village - location ?medallion - item)
    :precondition (and (player-at ?p ?cave) (ally-present ?native ?cave) (at-collapsed-cave) (not (medallion-found)))
    :effect (and (medallion-found) (has ?p ?medallion) (not (player-at ?p ?cave)) (player-at ?p ?village) (ally-present ?native ?village) (not (at-collapsed-cave)) (at-village) (native-trust-earned))
  )
  (:action explore-jungle-outskirts-with-ally
    :parameters (?p - player ?native - ally ?jungle_edge - location)
    :precondition (and (player-at ?p ?jungle_edge) (ally-present ?native ?jungle_edge) (at-jungle-edge) (not (wounded ?p)))
    :effect (and)
  )
  (:action gain-ally-trust-with-gift
    :parameters (?p - player ?native - ally ?shore - location)
    :precondition (and (player-at ?p ?shore) (at-shore) (not (ally-present ?native ?shore)))
    :effect (and (ally-present ?native ?shore))
  )
  (:action insist-on-alone
    :parameters (?p - player ?native - ally ?shore - location ?jungle_edge - location)
    :precondition (and (player-at ?p ?shore) (at-shore) (not (ally-present ?native ?shore)))
    :effect (and (not (ally-present ?native ?shore)) (not (player-at ?p ?shore)) (player-at ?p ?jungle_edge) (not (at-shore)) (at-jungle-edge))
  )
  (:action ask-native-for-guidance
    :parameters (?p - player ?native - ally ?shore - location ?jungle_edge - location)
    :precondition (and (player-at ?p ?shore) (ally-present ?native ?shore) (at-shore))
    :effect (and (not (player-at ?p ?shore)) (player-at ?p ?jungle_edge) (not (at-shore)) (at-jungle-edge))
  )
  (:action visit-village-to-earn-trust
    :parameters (?p - player ?village - location)
    :precondition (and (player-at ?p ?village) (at-village) (not (native-trust-earned)) (medallion-found))
    :effect (and (native-trust-earned))
  )
  (:action attempt-negotiate-without-medallion
    :parameters (?p - player ?village - location)
    :precondition (and (player-at ?p ?village) (at-village) (not (medallion-found)))
    :effect (and (wounded ?p) (fatally-injured ?p))
  )
  (:action leave-village-to-find-medallion
    :parameters (?p - player ?village - location ?cave - location)
    :precondition (and (player-at ?p ?village) (at-village) (not (medallion-found)))
    :effect (and (not (player-at ?p ?village)) (player-at ?p ?cave) (not (at-village)) (at-collapsed-cave))
  )
  (:action rest-at-jungle-edge
    :parameters (?p - player ?jungle_edge - location)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge) (wounded ?p))
    :effect (and (not (wounded ?p)))
  )
  (:action travel-to-village-with-medallion
    :parameters (?p - player ?jungle_edge - location ?village - location ?medallion - item)
    :precondition (and (player-at ?p ?jungle_edge) (at-jungle-edge) (medallion-found) (has ?p ?medallion))
    :effect (and (not (player-at ?p ?jungle_edge)) (player-at ?p ?village) (not (at-jungle-edge)) (at-village))
  )
  (:action explore-jungle-outskirts-with-medallion
    :parameters (?p - player ?native - ally ?jungle_edge - location ?medallion - item)
    :precondition (and (player-at ?p ?jungle_edge) (ally-present ?native ?jungle_edge) (at-jungle-edge) (medallion-found) (has ?p ?medallion))
    :effect (and)
  )
  (:action earn-native-trust-at-village
    :parameters (?p - player ?village - location)
    :precondition (and (player-at ?p ?village) (at-village) (medallion-found) (not (native-trust-earned)))
    :effect (and (native-trust-earned))
  )
  (:action journey-to-temple-entrance
    :parameters (?p - player ?village - location ?temple - location)
    :precondition (and (player-at ?p ?village) (at-village) (native-trust-earned))
    :effect (and (not (player-at ?p ?village)) (player-at ?p ?temple) (not (at-village)) (temple-accessible))
  )
  (:action learn-altar-puzzle
    :parameters (?p - player ?village - location ?puzzle - puzzle)
    :precondition (and (player-at ?p ?village) (at-village) (native-trust-earned))
    :effect (and (puzzle-solved))
  )
  (:action rest-before-final-leg
    :parameters (?p - player ?village - location)
    :precondition (and (player-at ?p ?village) (at-village) (not (wounded ?p)))
    :effect (and)
  )
  (:action attempt-solve-altar-puzzle
    :parameters (?p - player ?temple - location ?puzzle - puzzle)
    :precondition (and (player-at ?p ?temple) (temple-accessible))
    :effect (and (puzzle-solved))
  )
  (:action search-temple-for-hints
    :parameters (?p - player ?temple - location)
    :precondition (and (player-at ?p ?temple) (temple-accessible) (not (wounded ?p)))
    :effect (and)
  )
  (:action enter-treasure-vault
    :parameters (?p - player ?temple - location)
    :precondition (and (player-at ?p ?temple) (temple-accessible) (puzzle-solved))
    :effect (and (treasure-claimed))
  )
  (:action inspect-treasure-for-traps
    :parameters (?p - player ?temple - location)
    :precondition (and (player-at ?p ?temple) (temple-accessible) (not (wounded ?p)))
    :effect (and)
  )
  (:action take-treasure-and-leave
    :parameters (?p - player ?temple - location)
    :precondition (and (player-at ?p ?temple) (temple-accessible) (puzzle-solved) (treasure-claimed))
    :effect (and)
  )
  (:action push-forward-to-find-medallion-wounded
    :parameters (?p - player ?cave - location ?medallion - item)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave) (wounded ?p))
    :effect (and (medallion-found) (has ?p ?medallion))
  )
  (:action retreat-to-jungle-edge-to-heal
    :parameters (?p - player ?cave - location ?jungle_edge - location)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave) (wounded ?p))
    :effect (and (not (wounded ?p)) (not (player-at ?p ?cave)) (player-at ?p ?jungle_edge) (not (at-collapsed-cave)) (at-jungle-edge))
  )
  (:action attempt-call-for-help-while-wounded
    :parameters (?p - player ?native - ally ?cave - location)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave) (wounded ?p) (not (ally-present ?native ?cave)))
    :effect (and (fatally-injured ?p))
  )
)