(define (domain brava-island-adventure)
  (:requirements :strips :typing)
  (:types player location item trap puzzle ally)
  (:predicates
    (player-at ?p - player ?l - location)
    (has ?p - player ?i - item)
    (ally-present ?a - ally ?l - location)
    (at-shore ?p - player)
    (at-jungle-edge ?p - player)
    (at-village ?p - player)
    (at-collapsed-cave ?p - player)
    (at-temple-entrance ?p - player)
    (medallion-found ?p - player)
    (native-trust-earned ?p - player)
    (puzzle-solved ?p - player)
    (treasure-claimed ?p - player)
    (wounded ?p - player)
    (storm-coming)
    (trap-active ?t - trap ?l - location)
    (trap-triggered ?t - trap ?l - location)
    (puzzle-active ?z - puzzle ?l - location)
  )
  (:constants altar-puzzle - puzzle)
  (:action take-direct-jungle-path
    :parameters (?p - player ?shore - location ?jungle - location)
    :precondition (and (player-at ?p ?shore) (at-shore ?p))
    :effect (and (player-at ?p ?jungle) (at-jungle-edge ?p) (not (player-at ?p ?shore)) (not (at-shore ?p)) (wounded ?p))
  )
  (:action follow-coastal-trail
    :parameters (?p - player ?shore - location ?jungle - location)
    :precondition (and (player-at ?p ?shore) (at-shore ?p))
    :effect (and (player-at ?p ?jungle) (at-jungle-edge ?p) (not (player-at ?p ?shore)) (not (at-shore ?p)) (not (wounded ?p)))
  )
  (:action press-on-to-collapsed-cave-despite-wound
    :parameters (?p - player ?jungle - location ?cave - location)
    :precondition (and (player-at ?p ?jungle) (at-jungle-edge ?p) (wounded ?p))
    :effect (and (player-at ?p ?cave) (at-collapsed-cave ?p) (wounded ?p) (not (player-at ?p ?jungle)) (not (at-jungle-edge ?p)))
  )
  (:action retreat-to-coastal-trail-to-heal
    :parameters (?p - player ?jungle - location ?shore - location)
    :precondition (and (player-at ?p ?jungle) (at-jungle-edge ?p) (wounded ?p))
    :effect (and (player-at ?p ?shore) (at-shore ?p) (wounded ?p) (not (player-at ?p ?jungle)) (not (at-jungle-edge ?p)))
  )
  (:action investigate-footprints
    :parameters (?p - player ?jungle - location ?a - ally)
    :precondition (and (player-at ?p ?jungle) (at-jungle-edge ?p) (not (wounded ?p)))
    :effect (and (ally-present ?a ?jungle) (not (wounded ?p)))
  )
  (:action head-directly-to-collapsed-cave
    :parameters (?p - player ?jungle - location ?cave - location)
    :precondition (and (player-at ?p ?jungle) (at-jungle-edge ?p) (not (wounded ?p)))
    :effect (and (player-at ?p ?cave) (at-collapsed-cave ?p) (not (player-at ?p ?jungle)) (not (at-jungle-edge ?p)))
  )
  (:action disarm-traps-carefully
    :parameters (?p - player ?cave - location)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave ?p))
    :effect (and (medallion-found ?p) (not (wounded ?p)))
  )
  (:action move-quickly-through-cave
    :parameters (?p - player ?cave - location)
    :precondition (and (player-at ?p ?cave) (at-collapsed-cave ?p))
    :effect (and (medallion-found ?p) (wounded ?p))
  )
  (:action trust-ally-completely
    :parameters (?p - player ?a - ally ?cave - location)
    :precondition (and (player-at ?p ?cave) (ally-present ?a ?cave) (medallion-found ?p))
    :effect (and (at-collapsed-cave ?p) (ally-present ?a ?cave))
  )
  (:action keep-cautious-distance
    :parameters (?p - player ?a - ally ?cave - location)
    :precondition (and (player-at ?p ?cave) (ally-present ?a ?cave) (medallion-found ?p))
    :effect (and (at-collapsed-cave ?p) (ally-present ?a ?cave))
  )
  (:action hurry-to-village-through-storm
    :parameters (?p - player ?cave - location ?village - location)
    :precondition (and (player-at ?p ?cave) (medallion-found ?p))
    :effect (and (player-at ?p ?village) (at-village ?p) (wounded ?p) (not (player-at ?p ?cave)) (not (at-collapsed-cave ?p)))
  )
  (:action seek-shelter-and-wait-out-storm
    :parameters (?p - player ?cave - location)
    :precondition (and (player-at ?p ?cave) (medallion-found ?p))
    :effect (and (storm-coming) (not (at-village ?p)))
  )
  (:action push-forward-to-village-despite-injury
    :parameters (?p - player ?cave - location ?village - location)
    :precondition (and (player-at ?p ?cave) (wounded ?p) (medallion-found ?p))
    :effect (and (player-at ?p ?village) (at-village ?p) (wounded ?p) (not (player-at ?p ?cave)) (not (at-collapsed-cave ?p)))
  )
  (:action treat-wound-before-moving-on
    :parameters (?p - player ?cave - location)
    :precondition (and (player-at ?p ?cave) (wounded ?p) (medallion-found ?p))
    :effect (and (not (wounded ?p)) (not (at-village ?p)))
  )
  (:action present-medallion-respectfully-to-elders
    :parameters (?p - player ?a - ally ?village - location)
    :precondition (and (player-at ?p ?village) (ally-present ?a ?village) (medallion-found ?p))
    :effect (and (native-trust-earned ?p) (at-village ?p) (ally-present ?a ?village))
  )
  (:action attempt-to-sneak-into-village
    :parameters (?p - player ?a - ally ?village - location)
    :precondition (and (player-at ?p ?village) (ally-present ?a ?village) (medallion-found ?p))
    :effect (and (not (native-trust-earned ?p)) (at-village ?p) (ally-present ?a ?village))
  )
  (:action explain-quest-openly-and-show-medallion
    :parameters (?p - player ?village - location)
    :precondition (and (player-at ?p ?village) (medallion-found ?p))
    :effect (and (native-trust-earned ?p) (at-village ?p))
  )
  (:action offer-gifts-to-villagers-to-gain-favor
    :parameters (?p - player ?village - location)
    :precondition (and (player-at ?p ?village) (medallion-found ?p))
    :effect (and (native-trust-earned ?p) (at-village ?p))
  )
  (:action act-defensively-and-prepare-for-conflict
    :parameters (?p - player ?village - location ?a - ally)
    :precondition (and (player-at ?p ?village) (medallion-found ?p))
    :effect (and (not (native-trust-earned ?p)) (wounded ?p) (at-village ?p) (ally-present ?a ?village))
  )
  (:action proceed-cautiously-to-village
    :parameters (?p - player ?village - location)
    :precondition (storm-coming)
    :effect (and (player-at ?p ?village) (at-village ?p) (not (storm-coming)))
  )
  (:action try-to-find-alternate-path-to-village
    :parameters (?p - player ?village - location)
    :precondition (storm-coming)
    :effect (and (not (at-village ?p)) (wounded ?p) (not (storm-coming)))
  )
  (:action travel-directly-to-temple-entrance
    :parameters (?p - player ?village - location ?temple - location)
    :precondition (and (player-at ?p ?village) (native-trust-earned ?p))
    :effect (and (player-at ?p ?temple) (at-temple-entrance ?p) (not (player-at ?p ?village)) (not (at-village ?p)))
  )
  (:action spend-time-with-natives-to-learn-puzzle
    :parameters (?p - player ?a - ally ?village - location)
    :precondition (and (player-at ?p ?village) (native-trust-earned ?p))
    :effect (and (ally-present ?a ?village) (puzzle-active altar-puzzle ?village) (at-village ?p))
  )
  (:action enter-temple-and-attempt-puzzle-immediately
    :parameters (?p - player ?temple - location)
    :precondition (and (player-at ?p ?temple) (at-temple-entrance ?p))
    :effect (puzzle-active altar-puzzle ?temple)
  )
  (:action rest-longer-to-ensure-readiness
    :parameters (?p - player)
    :precondition (wounded ?p)
    :effect (not (wounded ?p))
  )
  (:action proceed-to-temple-entrance-to-solve-puzzle
    :parameters (?p - player ?a - ally ?village - location ?temple - location)
    :precondition (and (player-at ?p ?village) (ally-present ?a ?village))
    :effect (and (player-at ?p ?temple) (at-temple-entrance ?p) (not (player-at ?p ?village)) (not (at-village ?p)))
  )
  (:action focus-carefully-and-solve-puzzle
    :parameters (?p - player ?temple - location ?z - puzzle)
    :precondition (and (player-at ?p ?temple) (puzzle-active ?z ?temple))
    :effect (and (puzzle-solved ?p) (treasure-claimed ?p) (not (puzzle-active ?z ?temple)))
  )
  (:action force-mechanism-quickly
    :parameters (?p - player ?temple - location ?z - puzzle ?t - trap)
    :precondition (and (player-at ?p ?temple) (puzzle-active ?z ?temple))
    :effect (and (not (puzzle-solved ?p)) (wounded ?p) (trap-triggered ?t ?temple) (not (puzzle-active ?z ?temple)))
  )
)